// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard";
import * as shared from "./index";

export const makeServer = (routes: autoguard.api.Server<shared.Autoguard.Requests, shared.Autoguard.Responses>, options?: Partial<{ urlPrefix: string }>): autoguard.api.RequestListener => {
	let endpoints = new Array<autoguard.api.Endpoint>();
	endpoints.push((raw, auxillary) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("food")]);
		components.push(["food_id", raw.components[1]]);
		components.push(["", decodeURIComponent("")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			validateRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["food_id"] = autoguard.api.getNumberOption(components, "food_id");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/food/<food_id>/"];
				let request = guard.as({ options, headers, payload }, "request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/food/<food_id>/"](new autoguard.api.ClientRequest(request, auxillary));
						return {
							validateResponse: async () => {
								let guard = shared.Autoguard.Responses["GET:/food/<food_id>/"];
								guard.as(response, "response");
								return response;
							}
						};
					}
				};
			}
		};
	});
	endpoints.push((raw, auxillary) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["filename", raw.components[0]]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			validateRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["filename"] = autoguard.api.getStringOption(components, "filename");
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["GET:/<filename>"];
				let request = guard.as({ options, headers, payload }, "request");
				return {
					handleRequest: async () => {
						let response = await routes["GET:/<filename>"](new autoguard.api.ClientRequest(request, auxillary));
						return {
							validateResponse: async () => {
								let guard = shared.Autoguard.Responses["GET:/<filename>"];
								guard.as(response, "response");
								return response;
							}
						};
					}
				};
			}
		};
	});
	return (request, response) => autoguard.api.route(endpoints, request, response, options?.urlPrefix);
};
