// This file was auto-generated by @joelek/ts-autoguard. Edit at own risk.

import * as autoguard from "@joelek/ts-autoguard";
import * as shared from "./index";

export const makeServer = (routes: autoguard.api.Server<shared.Autoguard.Requests, shared.Autoguard.Responses>, options?: Partial<{ urlPrefix: string }>): autoguard.api.RequestListener => {
	let endpoints = new Array<autoguard.api.Endpoint>();
	endpoints.push((raw, auxillary) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["", decodeURIComponent("food")]);
		components.push(["food_id", raw.components[1]]);
		components.push(["", decodeURIComponent("")]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			validateRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["food_id"] = autoguard.api.getValue(components, "food_id", false);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["getFood"];
				let request = guard.as({ options, headers, payload }, "request");
				return {
					handleRequest: async () => {
						let response = await routes["getFood"](new autoguard.api.ClientRequest(request, auxillary));
						return {
							validateResponse: async () => {
								let guard = shared.Autoguard.Responses["getFood"];
								guard.as(response, "response");
								let status = response.status ?? 200;
								let headers = new Array<[string, string]>();
								headers.push(...autoguard.api.extractKeyValuePairs(response.headers ?? {}, headers.map((header) => header[0])));
								let payload = autoguard.api.serializePayload(response.payload);
								return autoguard.api.finalizeResponse({ status, headers, payload }, "application/json; charset=utf-8");
							}
						};
					}
				};
			}
		};
	});
	endpoints.push((raw, auxillary) => {
		let method = "GET";
		let components = new Array<[string, string]>();
		components.push(["filename", raw.components[0]]);
		return {
			acceptsComponents: () => autoguard.api.acceptsComponents(raw.components, components),
			acceptsMethod: () => autoguard.api.acceptsMethod(raw.method, method),
			validateRequest: async () => {
				let options = autoguard.api.combineKeyValuePairs(raw.parameters);
				options["filename"] = autoguard.api.getValue(components, "filename", true);
				let headers = autoguard.api.combineKeyValuePairs(raw.headers);
				let payload = await autoguard.api.deserializePayload(raw.payload);
				let guard = shared.Autoguard.Requests["getStaticContent"];
				let request = guard.as({ options, headers, payload }, "request");
				return {
					handleRequest: async () => {
						let response = await routes["getStaticContent"](new autoguard.api.ClientRequest(request, auxillary));
						return {
							validateResponse: async () => {
								let guard = shared.Autoguard.Responses["getStaticContent"];
								guard.as(response, "response");
								let status = response.status ?? 200;
								let headers = new Array<[string, string]>();
								headers.push(...autoguard.api.extractKeyValuePairs(response.headers ?? {}, headers.map((header) => header[0])));
								let payload = response.payload;
								return autoguard.api.finalizeResponse({ status, headers, payload }, "application/octet-stream");
							}
						};
					}
				};
			}
		};
	});
	return (request, response) => autoguard.api.route(endpoints, request, response, options?.urlPrefix);
};
